### ISSUE TITLE
envFrom uses wrong indentation

### ISSUE THREAD

**Issue by Deaddy** [Sciebo-RDS/port_datasafe#1]
deployment.yaml currently has
```
          envFrom:
          - configMapRef:
            name: mservice
          - configMapRef:
            name: proxy
          - configMapRef:
            name: globalenvvar
          - configMapRef:
            name: portdatasafeconfig

```
https://github.com/Sciebo-RDS/port_datasafe/blob/master/charts/templates/deployment.yaml#L36

But the `name: ...` should be indented one level further.
